services:
  arrows:
    restart: unless-stopped
    image: ghcr.io/simoneguzzi/arrows.app:0.1.0
    expose:
      - "4200"
    labels:
      - "traefik.http.routers.arrows.rule=PathPrefix(`/`)"
    volumes:
      - ./services/arrows/.env:/app/apps/arrows-ts/.env

  gen-pydantic:
    restart: unless-stopped
    image: ghcr.io/simoneguzzi/gen-pydantic:latest
    expose:
      - "8000"
    labels:
      - "traefik.http.routers.gen-pydantic.rule=PathPrefix(`/gen-pydantic`)"

  traefik:
    restart: unless-stopped
    image: docker.io/library/traefik:v3.1.0
    command: --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
