services:
  arrows:
    restart: unless-stopped
    image: ghcr.io/simoneguzzi/arrows.app:0.4.0
    expose:
      - "4200"
    volumes:
      - ./services/arrows/.env:/app/apps/arrows-ts/.env

  gen-pydantic:
    restart: unless-stopped
    image: ghcr.io/simoneguzzi/gen-pydantic:0.2.0
    expose:
      - "8000"
