services:
  arrows:
    restart: unless-stopped
    image: ghcr.io/simoneguzzi/arrows.app:0.4.0
    environment:
      VITE_GEN_PYDANTIC_ENDPOINT: "https://{{ ansible_host }}/api/gen-pydantic/"
      VITE_VALIDATE_LINKML_ENDPOINT: "https://{{ ansible_host }}/api/validate-linkml/"
    expose:
      - "4200"

  gen-pydantic:
    restart: unless-stopped
    image: ghcr.io/simoneguzzi/gen-pydantic:0.3.0
    environment:
      OPENAI_API_KEY: "{{ openai_api_key }}"
      OPENAI_THREAD_ID: "{{ openai_thread_id }}"
      OPENAI_ASSISTANT_ID: "{{ openai_assistant_id }}"
    expose:
      - "8000"
